# Generated by Django 3.2.23 on 2024-01-26 23:13

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.product_image_file_path)),
                ('category', models.TextField(choices=[('Crop Tops', 'Crop Tops'), ('Hoodies', 'Hoodies'), ('Joggers', 'Joggers'), ('Shorts', 'Shorts'), ('Sports Bra', 'Sports Bra'), ('Underwear', 'Underwear')], null=True)),
                ('gender', models.TextField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
